### ISSUE TITLE
Version Bump to 1.1.0

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/xref_runner#64]
After #61

**Comment by dumbbell** [comment]
If I may, I would love to see a new release, in particular one which would include an upload of a compiled escript to the GitHub release.

After that, I will submit a patch to Erlang.mk to update the link to this compiled escript. My end goal is to use xrefr in RabbitMQ CI (that's why I needed #66).

**Comment by dumbbell** [comment]
Thank you very much!
